[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "python app.py"
  port = 5000
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 