[build]
  publish = "."
  command = "bash netlify-build.sh"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200

[dev]
  command = "python app.py"
  framework = "#custom"
  port = 5000
  targetPort = 5000
